"""Add roles of user

Revision ID: 516b4b64621c
Revises: 845f36ad69ea
Create Date: 2023-02-24 20:37:43.316734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516b4b64621c'
down_revision = '845f36ad69ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
